default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mycards_development

test:
  <<: *default
  database: mycards_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# These can stay as SQLite since they're just for caching/jobs
# and don't need to persist long-term
cache:
  adapter: sqlite3
  database: storage/production_cache.sqlite3
  migrations_paths: db/cache_migrate

queue:
  adapter: sqlite3
  database: storage/production_queue.sqlite3
  migrations_paths: db/queue_migrate

cable:
  adapter: sqlite3
  database: storage/production_cable.sqlite3
  migrations_paths: db/cable_migrate
